previsao = {'DailyForecasts': [
{'Date': '2021-01-16T07:00:00-03:00',
'Day': {'HasPrecipitation': True,
        'Icon': 14,
        'IconPhrase': 'Parcialmente aberto, com pancadas de chuva',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'EpochDate': 1610791200,
'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=1&unit=c&lang=pt-br',
'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=1&unit=c&lang=pt-br',
'Night': {'HasPrecipitation': True,
        'Icon': 35,
        'IconPhrase': 'Parcialmente nublado',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'Sources': ['AccuWeather'],
'Temperature': {'Maximum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 30.0},
                'Minimum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 25.3}}},
{'Date': '2021-01-17T07:00:00-03:00',
'Day': {'HasPrecipitation': True,
        'Icon': 2,
        'IconPhrase': 'Predominantemente ensolarado',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'EpochDate': 1610877600,
'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=2&unit=c&lang=pt-br',
'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=2&unit=c&lang=pt-br',
'Night': {'HasPrecipitation': True,
        'Icon': 39,
        'IconPhrase': 'Parcialmente nublado, com pancadas de chuva',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'Sources': ['AccuWeather'],
'Temperature': {'Maximum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 30.0},
                'Minimum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 25.0}}},
{'Date': '2021-01-18T07:00:00-03:00',
'Day': {'HasPrecipitation': False,
        'Icon': 2,
        'IconPhrase': 'Predominantemente ensolarado'},
'EpochDate': 1610964000,
'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=3&unit=c&lang=pt-br',
'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=3&unit=c&lang=pt-br',
'Night': {'HasPrecipitation': True,
        'Icon': 36,
        'IconPhrase': 'Nuvens esparsas',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'Sources': ['AccuWeather'],
'Temperature': {'Maximum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 30.2},
                'Minimum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 25.1}}},
{'Date': '2021-01-19T07:00:00-03:00',
'Day': {'HasPrecipitation': True,
        'Icon': 3,
        'IconPhrase': 'Parcialmente ensolarado',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'EpochDate': 1611050400,
'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=4&unit=c&lang=pt-br',
'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=4&unit=c&lang=pt-br',
'Night': {'HasPrecipitation': True,
        'Icon': 35,
        'IconPhrase': 'Parcialmente nublado',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'Sources': ['AccuWeather'],
'Temperature': {'Maximum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 30.0},
                'Minimum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 25.1}}},
{'Date': '2021-01-20T07:00:00-03:00',
'Day': {'HasPrecipitation': True,
        'Icon': 3,
        'IconPhrase': 'Parcialmente ensolarado',
        'PrecipitationIntensity': 'Light',
        'PrecipitationType': 'Rain'},
'EpochDate': 1611136800,
'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=5&unit=c&lang=pt-br',
'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?day=5&unit=c&lang=pt-br',
'Night': {'HasPrecipitation': True,
        'Icon': 40,
        'IconPhrase': 'Predominantemente nublado, com pancadas de chuva',
        'PrecipitationIntensity': 'Moderate',
        'PrecipitationType': 'Rain'},
'Sources': ['AccuWeather'],
'Temperature': {'Maximum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 29.8},
                'Minimum': {'Unit': 'C',
                            'UnitType': 17,
                            'Value': 25.4}}}],
'Headline': {'Category': 'rain',
            'EffectiveDate': '2021-01-16T22:00:00-03:00',
            'EffectiveEpochDate': 1610845200,
            'EndDate': '2021-01-17T04:00:00-03:00',
            'EndEpochDate': 1610866800,
            'Link': 'http://www.accuweather.com/pt/br/santa-maria/2726453/daily-weather-forecast/2726453?unit=c&lang=pt-br',
            'MobileLink': 'http://m.accuweather.com/pt/br/santa-maria/2726453/extended-weather-forecast/2726453?unit=c&lang=pt-br',
            'Severity': 5,
            'Text': 'Previsão de pancadas de chuva hoje no meio da noite'}}